<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            "10th of Ramadan",
            "15th of May",
            "6th of October",
            "Abu El Matamir",
            "Abu Hummus",
            "Abu Tesht",
            "Akhmim",
            "Al Khankah",
            "Alexandria",
            "Arish",
            "Ashmoun",
            "Aswan",
            "Asyut",
            "Awsim",
            "Badr",
            "Baltim",
            "Banha",
            "Basyoun",
            "Biyala",
            "Belqas",
            "Beni Mazar",
            "Beni Suef",
            "Beni Ebeid",
            "Biba",
            "Bilbeis",
            "Birket El Sab",
            "Borg El Arab",
            "Borg El Burullus[1]",
            "Bush",
            "Cairo",
            "Dahab",
            "Dairut",
            "Damanhur",
            "Damietta",
            "Dar El Salam",
            "Daraw",
            "Deir Mawas",
            "Dekernes",
            "Dendera",
            "Desouk",
            "Dishna",
            "Edfu",
            "Edku",
            "El Alamein",
            "El Arish",
            "El Ayyat",
            "El Badari",
            "El Badrashein",
            "El Bagour",
            "El Balyana",
            "El Basaliya",
            "El Bayadiya",
            "El Dabaa",
            "El Delengath",
            "El Fashn",
            "El Gamaliya",
            "El Ghanayem",
            "El Hamool",
            "El Hamam",
            "El Hawamdeya",
            "El Husseiniya",
            "El Idwa",
            "El Ibrahimiya",
            "El Kanayat",
            "El Kareen",
            "El Mahalla El Kubra",
            "El Mahmoudiyah",
            "El Mansha",
            "El Manzala",
            "El Maragha",
            "El Matareya",
            "El Qantara",
            "El Qanater", "El Khayreya",
            "El Qoseir",
            "El Qusiya",
            "El Rahmaniya",
            "El Reyad",
            "El Rhoda",
            "El Saff",
            "El Santa",
            "El Sarw",
            "El Sebaiya",
            "El Senbellawein",
            "El Shohada",
            "El Shorouk",
            "El Tor",
            "El Waqf",
            "El Wasta",
            "El Zarqa",
            "Esna",
            "Ezbet El Borg",
            "Faqous",
            "Faraskur",
            "Farshut",
            "Fayed",
            "Faiyum",
            "Fuka",
            "Girga",
            "Giza",
            "Hihya",
            "Hosh Essa",
            "Hurghada",
            "Ibsheway",
            "Ihnasiya",
            "Ismailia",
            "Itay El Barud",
            "Itsa",
            "Juhayna",
            "Kafr El Sheikh",
            "Kafr El Zayat",
            "Kafr El Batikh",
            "Kafr El Dawwar",
            "Kafr Saad",
            "Kafr Saqr",
            "Kafr Shukr",
            "Kafr Zarqan",
            "Kerdasa",
            "Khanka",
            "Kharga",
            "Khusus",
            "Kom Hamada",
            "Kom Ombo",
            "Kotoor",
            "Luxor",
            "Maghagha",
            "Mallawi",
            "Manfalut",
            "Mansoura",
            "Mashtool El Souk",
            "Matai",
            "Menouf",
            "Marsa Alam",
            "Mersa Matruh",
            "Metoubes",
            "Minya",
            "Minyet El Nasr",
            "Mit Abu El Kom",
            "Mit Abu Ghaleb",
            "Mit Adlan",
            "Mit Bera",
            "Mit El Korama",
            "Mit Elwan",
            "Mit Fadala",
            "Mit Ghamr",
            "Mit Kenana",
            "Mit Rahina",
            "Mit Salsil",
            "Mit Sudan",
            "Mit Yazid",
            "Monsha'at El-Qanater",
            "Mut",
            "Nabaroh",
            "Nag Hammadi",
            "Naqada",
            "New Administrative Capital (NAC)",
            "New Alamein",
            "New Aswan",
            "New Akhmim",
            "New Asyut",
            "New Beni Suef",
            "New Borg El Arab",
            "New Cairo",
            "New Damietta",
            "New Faiyum",
            "New Minya",
            "New Nubariya",
        ];

        foreach ($cities as $city) {
            City::updateOrCreate([
                'name'  =>  $city
            ]);
        }
    }
}
